services:
  - type: web
    name: bookstore-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node app.js
    repo: https://github.com/Sulaimonyusuf123/BookStore
    branch: master